### ISSUE TITLE
The base tag renders twice for the first item in a list.

### ISSUE THREAD

**Issue by noellecdv0** [darrenkuro/obsidian-basetag#1]
I LOVE this plugin and it's exactly what I was looking for to mitigate my long tags (since I love nesting). The only problem I've noticed is that the first task or item in any given list renders the base stage it's tagged with twice. Screenshot below:

![image](https://user-images.githubusercontent.com/98427340/211175494-1f25e4e0-7d07-4c27-8906-3225191ceafd.png)

**Comment by darrenkuro** [comment]
This is likely due to a clash with a competing post markdown renderer by another plugin. Do you mind sharing a list of your enabled plugins?

**Comment by noellecdv0** [comment]
I have quite a few plugins installed. Here are screenshots of them all.
![image](https://user-images.githubusercontent.com/98427340/211223809-d44f0bfb-abbf-4032-a6d2-d03c9f87eac6.png)
![image](https://user-images.githubusercontent.com/98427340/211223835-a74186a9-fe92-4717-8fd1-8d4e20ff71e8.png)
![image](https://user-images.githubusercontent.com/98427340/211223848-4fa43231-26a9-4887-be94-17bc392b2de9.png)
![image](https://user-images.githubusercontent.com/98427340/211223854-97e84d2a-8c1e-4ab7-bd06-cba0c6b1516d.png)
![image](https://user-images.githubusercontent.com/98427340/211223865-ec27680c-a60a-422f-a1aa-3bba2e7d87de.png)

**Comment by darrenkuro** [comment]
Fixed. Try update to the new version, it should work fine now. Thanks for reporting! 

(Note: problem was custom rendering in dataviewjs code block, same element went through postprocessor multiple times, added a class to prevent tags already rendered from rendering again.)

**Comment by darrenkuro** [comment]
Oops, minor hiccup, now it should be working. :)
