### ISSUE TITLE
Support `obsidian-colorful-tag` plugin in Editing View

### ISSUE THREAD

**Issue by hewcaw** [darrenkuro/obsidian-basetag#3]
I'm using https://github.com/rien7/obsidian-colorful-tag to customize the tag's appearance, Reading View works flawlessly.

**Comment by darrenkuro** [comment]
Sorry for the late reply, change an attribute and it should work with most of its functions as long as this plugin doesn't change its css selector. Let me know if there's any issue. :)

**Comment by hewcaw** [comment]
Wait so long I switched to Logseq.

<details>
I'm kidding, appreciate it a lot brother 😘 But dang! 
</details>
