### ISSUE TITLE
It should be disabled in source mode

### ISSUE THREAD

**Issue by nununo** [darrenkuro/obsidian-basetag#5]
Hello,

Source mode should be showing exactly the actual source code. Yet, this plugin is still active in source mode.
Would it be possible to disable it in source mode or at least to make it optional?

Thank you!

**Comment by darrenkuro** [comment]
The original idea was this was going to be a super lightweight plugin and I didn't really want setting tabs to be clogged up by it; but I guess it makes sense so added a setting to disable it. Should be working. Cheers.
